version: '3.1'

services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: "myuser"
      FTP_PASS: "mypass"
      PASV_ADDRESS: "127.0.0.1"
      PASV_MIN_PORT: "21100"
      PASV_MAX_PORT: "21110"
    volumes:
      - /data/ftp:/home/vsftpd